services:
  whatsapp-connector:
    build: .
    image: whatsapp-connector
    container_name: whatsapp-connector
    ports:
      - "9010:9010"
    env_file:
      - .env
    environment:
      TZ: Europe/Kiev
    restart: always
    networks:
      - think-root-network

networks:
  think-root-network:
    external: true