services:
  wapp:
    build: .
    image: wapp
    container_name: wapp
    ports:
      - "9010:9010"
    env_file:
      - .env
    environment:
      TZ: Europe/Kiev
    restart: always
    networks:
      - chappie_network

networks:
  chappie_network:
    external: true